server:
  port: 8080

spring:
  application:
    name: rpc-demo-consumer
  thymeleaf:
    cache: false
    prefix: classpath:/templates/
    suffix: .html
    encoding: UTF-8
    mode: HTML

logging:
  level:
    root: INFO
    com.rpc: DEBUG 